
image: node:latest

stages:
  - installation
  - test_scanner

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: installation
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
test_abstract_scanner:
  stage: test_scanner
  script:
    - npm run coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
